In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,5],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [ ]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    5
3     5             12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import layers, Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(2, activation='linear',input_dim=2))
model.add(Dense(1,activation = 'linear'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[-0.2351737 ,  0.03026831],
        [-0.34613937, -0.842651  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.6757333 ],
        [-0.30003798]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1,0.1],
 [0.1,0.1]], dtype = np.float32),
               np.array([0.,0.], dtype = np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype = np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs = 75, verbose = 1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 23.3435 
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 22.3961
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 23.3206
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 20.9789
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 20.6744
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 18.7478 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 24.4251 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 28.3343 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 28.4344
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 21.6851
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 22.8746 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 18.1264
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 22.0526 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 19.3972
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 15.6549 
Epoch 16/75
4