In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns = ['cgpa', 'profile_score', 'lpa'])

In [ ]:
df.head()

cgpa  profile_score  lpa
0     8              8    1
1     7              9    1
2     6             10    0
3     5              5    0

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential, layers
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(2, activation= 'sigmoid', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_7 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 0.6102396, -0.7928279],
        [ 0.9159175,  0.9816588]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.15225029],
        [0.09068513]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [np.array([[0.1,  0.1],
        [0.1,  0.1 ]], dtype=np.float32),
 np.array([0., 0.], dtype=np.float32),
 np.array([[0.1 ],
        [ 0.1]], dtype=np.float32),
 np.array([0.], dtype=np.float32)]

model.set_weights(new_weights)

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'binary_crossentropy', optimizer = optimizer)

In [ ]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=75, verbose = 1, batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 33ms/step - loss: 0.6572
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.6556 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7346 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.6553 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.7338
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6826
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6732
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7329
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.6569 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.7170
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6827
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6572
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6838
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7317
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.7061
Epoch 16/75
4/4 ━━━━━━━━━━━━━━